# Generated by Django 5.2.5 on 2025-08-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_council_events_gallery_rename_homecontent_contacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='location',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='title',
        ),
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='name',
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contacts',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='council',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='council',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='council',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='council',
            name='post',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='council',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='councils/'),
        ),
    ]
