# Generated by Django 5.2.5 on 2025-08-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_location_events_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousWorkshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('alt', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'PreviousWorkshops',
            },
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='workshops/')),
                ('instructors', models.TextField()),
                ('mode', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('registration_fees', models.CharField(max_length=50)),
                ('registration_url', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('benefits', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Workshops',
            },
        ),
    ]
