# Generated by Django 5.2.5 on 2025-08-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_previousworkshops_workshops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshops',
            old_name='registration_fees',
            new_name='fees',
        ),
        migrations.RenameField(
            model_name='workshops',
            old_name='registration_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='workshops',
            name='highlights',
            field=models.JSONField(default=list),
        ),
    ]
