# Generated by Django 5.2.5 on 2025-08-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_registration_fees_workshops_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='schedule',
            field=models.JSONField(default=list),
        ),
    ]
