# Generated by Django 5.2.5 on 2025-08-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workshops_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='instructors',
            field=models.JSONField(default=list),
        ),
    ]
