# Generated by Django 5.2.5 on 2025-08-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_workshops_instructors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='instructors',
            field=models.TextField(),
        ),
    ]
