# Generated by Django 5.2.5 on 2025-08-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_workshops_instructors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='instructors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
