# Generated by Django 5.2.5 on 2025-08-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_phdcppc_phddppc_phdsppc_ugcouncil'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='language/')),
            ],
            options={
                'verbose_name_plural': 'LanguageTeam',
            },
        ),
    ]
