# Generated by Django 5.2.5 on 2025-08-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_languageteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='lectures/')),
                ('instructors', models.JSONField(blank=True, default=list, null=True)),
                ('mode', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('schedule', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('location', models.CharField(max_length=200)),
                ('benefits', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'LanguageCourses',
            },
        ),
    ]
