# Generated by Django 5.2.5 on 2025-09-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_council_photo_alter_events_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshops',
            old_name='photo',
            new_name='poster',
        ),
    ]
