# Generated by Django 5.2.5 on 2025-09-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_photo_workshops_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshops',
            old_name='poster',
            new_name='photo',
        ),
    ]
