# Generated by Django 5.2.5 on 2025-09-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_poster_workshops_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchRepresentatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='br_photos/')),
                ('tenure', models.CharField(choices=[('2024-28', '2024-28'), ('2023-27', '2023-27'), ('2022-26', '2022-26')], default='2024-28', max_length=7)),
            ],
        ),
    ]
