# Generated by Django 5.2.5 on 2025-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_branchrepresentatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchrepresentatives',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='branch_reps/'),
        ),
    ]
