# Generated by Django 5.2.5 on 2025-09-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_branchrepresentatives_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchRepresentatives',
            new_name='BranchRepresentative',
        ),
    ]
