# Generated by Django 5.2.5 on 2025-09-25 03:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_branchrepresentatives_branchrepresentative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchrepresentative',
            options={'verbose_name_plural': 'BranchRepresentatives'},
        ),
        migrations.AlterField(
            model_name='branchrepresentative',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
