# Generated by Django 5.2.5 on 2025-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_branchrepresentative_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='tenure',
            field=models.CharField(default='2024-25', max_length=20),
        ),
    ]
