# Generated by Django 5.2.5 on 2025-09-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_council_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='tenure',
            field=models.CharField(default='2025-26', max_length=20),
        ),
    ]
