# Generated by Django 5.2.5 on 2025-09-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_council_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='tenure',
            field=models.CharField(max_length=20),
        ),
    ]
