# Generated by Django 5.2.5 on 2025-09-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_council_tenure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pal',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='pal',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='pal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pal',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='pal',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='pal',
            name='post',
        ),
    ]
