# Generated by Django 5.2.5 on 2025-09-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_photo_pal_image_rename_name_pal_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pal',
            old_name='image',
            new_name='photo',
        ),
    ]
