# Generated by Django 5.2.5 on 2025-10-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_image_pal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchrepresentative',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='branch_reps/'),
        ),
        migrations.AlterField(
            model_name='council',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='council/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='languagecourses',
            name='photo',
            field=models.ImageField(upload_to='language_courses/'),
        ),
        migrations.AlterField(
            model_name='languageteam',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='language_team/'),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='photo',
            field=models.ImageField(upload_to='lectures/'),
        ),
        migrations.AlterField(
            model_name='pal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pal/'),
        ),
        migrations.AlterField(
            model_name='phdcppc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='phd_cppc/'),
        ),
        migrations.AlterField(
            model_name='phddppc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='phd_dppc/'),
        ),
        migrations.AlterField(
            model_name='phdsppc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='phd_sppc/'),
        ),
        migrations.AlterField(
            model_name='ugcouncil',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ugcouncil/'),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='photo',
            field=models.ImageField(upload_to='workshops/'),
        ),
    ]
